mode:
  develop: true

server:
  port: 8090

db:
  dsn: root:root@tcp(localhost:3306)/gogofly?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 10 # 最多空闲连接数
  maxOpenConn: 10 # 最多打开连接数

redis:
  url: localhost:6379

jwt:
  tokenExpire: 3        # token有效时长(分钟)
  signingKey: gogofly.cn # 签名使用的Key

ansible:
  user:
    name: root
    password: abc123
  ShutdownHost:
    Args: "poweroff"

log:
  MaxSize: 1      # 日志文件最大的尺寸(M), 超限后开始自动分割
  MaxBackups: 10  # 保留旧文件的最大个数
  MaxAge: 90      # 保留旧文件的最大天数